spring:
  application:
    name: ai-manus
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/vector_database
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    google:
      genai:
        api-key: your-api-key
        embedding:
          text:
            options:
              model: text-embedding-004
              task-type: question_answering
        chat:
          options:
            model: gemini-2.5-flash-lite

#server:
#  port: 8123
#  servlet:
#    context-path: /api

knife4j:
  enable: true
  setting:
    language: en

search-api:
  api-key: your-api-key

logging:
  level:
    org.springframework.ai: DEBUG